/* IN THE VOID — PDF-only viewer bridge. Images and videos stay unchanged. */
(function(){
'use strict';
if(window.__inVoidPdfBridgeV3)return;
window.__inVoidPdfBridgeV3=true;
function viewerPath(){const p=window.location.pathname;return /\/app\/index\.html$/.test(p)?'../pdf-viewer.html':'./pdf-viewer.html'}
function openDedicatedPdf(frame){if(!frame||frame.dataset.inVoidPdfOpened==='1')return;const url=frame.getAttribute('src')||frame.src||'';if(!url||url==='about:blank')return;frame.dataset.inVoidPdfOpened='1';const title=document.querySelector('.midad-media-viewer-title')?.textContent?.trim()||'ملف PDF';const target=viewerPath()+'?url='+encodeURIComponent(url)+'&name='+encodeURIComponent(title);frame.src=target;frame.removeAttribute('sandbox');frame.style.width='100%';frame.style.height='100%';frame.style.border='0'}
function watchPdf(){document.querySelectorAll('iframe.midad-media-pdf').forEach(openDedicatedPdf)}
function installUnsupportedDownloadPage(){if(typeof window.openMaterialViewer!=='function'||typeof window.midadMediaType!=='function'||typeof window.midadGetMaterialUrl!=='function')return;if(window.openMaterialViewer.__inVoidWrapped)return;const original=window.openMaterialViewer;async function wrapped(item){const path=item?.filePath||item?.fileData||'';const name=item?.fileName||item?.name||'الملف';const type=window.midadMediaType(path,name);if(type==='unknown'&&path){try{const result=await window.midadGetMaterialUrl(path,type,name);if(!result?.url)throw new Error('تعذر الوصول إلى الملف');const page=new URL(viewerPath().replace('pdf-viewer.html','download-only.html'),window.location.href);page.searchParams.set('url',result.url);page.searchParams.set('name',name);window.location.assign(page.href);return}catch(e){if(typeof window.showToast==='function')window.showToast(e.message||'تعذر الوصول إلى الملف','error');return}}return original(item)}wrapped.__inVoidWrapped=true;window.openMaterialViewer=wrapped}
function installViewerZoom(){if(!/pdf-viewer\.html$/.test(location.pathname)||window.__inVoidViewerZoom)return;window.__inVoidViewerZoom=true;const c=document.getElementById('pdf-images-container');if(!c)return;let d0=0,s0=1,scale=1;function d(a,b){return Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY)}function apply(){c.style.transform='none';c.querySelectorAll('.pdf-page-img').forEach(img=>{img.style.width=Math.min(750,Math.max(c.clientWidth-20,260)*scale)+'px';img.style.maxWidth='none'})}c.style.touchAction='pan-x pan-y';c.addEventListener('touchstart',e=>{if(e.touches.length===2){d0=d(e.touches[0],e.touches[1]);s0=scale;c.style.touchAction='none'}},{passive:false});c.addEventListener('touchmove',e=>{if(e.touches.length!==2||!d0)return;e.preventDefault();scale=Math.max(1,Math.min(3,s0*d(e.touches[0],e.touches[1])/d0));apply()},{passive:false});c.addEventListener('touchend',e=>{if(e.touches.length<2){d0=0;c.style.touchAction='pan-x pan-y'}},{passive:true})}
function start(){watchPdf();installUnsupportedDownloadPage();installViewerZoom();const o=new MutationObserver(()=>{watchPdf();installUnsupportedDownloadPage();installViewerZoom()});if(document.body)o.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['src']});setInterval(()=>{watchPdf();installUnsupportedDownloadPage();installViewerZoom()},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
